const firebaseConfig={apiKey:"AIzaSyBX496oLlIFMD36SvyOl5zczX8d3vbvWEU",authDomain:"mineserver-bb0c6.firebaseapp.com",databaseURL:"https://mineserver-bb0c6-default-rtdb.europe-west1.firebasedatabase.app",projectId:"mineserver-bb0c6",storageBucket:"mineserver-bb0c6.firebasestorage.app",messagingSenderId:"630624618107",appId:"1:630624618107:web:4b2fdc9f2b7aaed44a44de",measurementId:"G-TEVM88WW3P"};
firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
const EMOJI_LIST=['👤','🎮','⚔️','🛡️','🧙','','🧝','🦁','','🐺','💀','','👾','🎯','','❄️','🔥','','☀️','🍀','💎','🔮','🗡️','','🌳','🌊','','🎨','📚','','🎧','🎬','','⭐','🌟','💫','','🎰','🎳','🎮'];
document.addEventListener('copy',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();showToast('Копирование запрещено')});
document.addEventListener('cut',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault()});
document.addEventListener('contextmenu',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();showToast('Правый клик отключён')});
document.addEventListener('selectstart',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault()});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if((e.ctrlKey&&['c','C','u','U','a','A','s','S'].includes(e.key))||e.key==='F12'||(e.ctrlKey&&e.shiftKey&&['I','i','J','j'].includes(e.key))){e.preventDefault();showToast('Действие заблокировано')}});
document.addEventListener('click',e=>{const r=document.createElement('div');r.className='ripple';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px';document.body.appendChild(r);setTimeout(()=>r.remove(),600)});
function copyIP(el){const ip=el.dataset.ip||'play.reished.ru';navigator.clipboard.writeText(ip).then(()=>{el.classList.add('copied');const c=el.querySelector('.copy');if(c){c.textContent='✓ скопировано';setTimeout(()=>{c.textContent='скопировать'},1500)}showToast('IP скопирован: '+ip)})}
function showToast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2000)}
async function ensureAdmin(){try{const a=await db.collection('users').doc('admin').get();if(!a.exists){await db.collection('users').doc('admin').set({password:'admin123',role:'admin',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('profiles').doc('admin').set({nickname:'admin',avatar:'👑',description:'Основатель сервера',status:'online',friends:[],background:''})}}catch(e){console.error(e)}}
function isAdmin(){return localStorage.getItem('ms_current')==='admin'}
function openAuth(){const m=document.getElementById('authModal');if(m)m.classList.add('active')}
function closeAuth(){const m=document.getElementById('authModal');if(m)m.classList.remove('active')}
function switchTab(tab){document.querySelectorAll('.modal-tab').forEach(t=>t.classList.remove('active'));document.querySelector(`.modal-tab[data-tab="${tab}"]`)?.classList.add('active');const l=document.getElementById('loginForm'),r=document.getElementById('registerForm');if(l)l.style.display=tab==='login'?'block':'none';if(r)r.style.display=tab==='register'?'block':'none'}
async function handleLogin(e){e.preventDefault();const n=document.getElementById('loginNick').value.trim(),p=document.getElementById('loginPass').value;try{const d=await db.collection('users').doc(n).get();if(!d.exists){showFormMsg('loginMsg','Пользователь не найден','error');return}if(d.data().password!==p){showFormMsg('loginMsg','Неверный пароль','error');return}localStorage.setItem('ms_current',n);await db.collection('profiles').doc(n).update({status:'online'});updateUserUI();closeAuth();showToast('Добро пожаловать, '+n+'!');if(n==='admin')setTimeout(()=>window.location.href='admin.html',800)}catch(e){console.error(e);showFormMsg('loginMsg','Ошибка входа','error')}}
async function handleRegister(e){e.preventDefault();const n=document.getElementById('regNick').value.trim(),p=document.getElementById('regPass').value,c=document.getElementById('regConfirm').value;if(n.toLowerCase()==='admin'){showFormMsg('regMsg','Этот ник зарезервирован','error');return}if(n.length<3){showFormMsg('regMsg','Ник минимум 3 символа','error');return}if(p.length<4){showFormMsg('regMsg','Пароль минимум 4 символа','error');return}if(p!==c){showFormMsg('regMsg','Пароли не совпадают','error');return}try{const s=await db.collection('users').get();const ex=s.docs.find(d=>d.id.toLowerCase()===n.toLowerCase());if(ex){showFormMsg('regMsg','Ник "'+ex.id+'" уже занят','error');return}await db.collection('users').doc(n).set({password:p,role:'player',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('profiles').doc(n).set({nickname:n,avatar:'',description:'Новый игрок',status:'online',friends:[],background:''});localStorage.setItem('ms_current',n);updateUserUI();closeAuth();showToast('Регистрация успешна! Привет, '+n+'!')}catch(e){console.error(e);showFormMsg('regMsg','Ошибка регистрации','error')}}
function logout(){const c=localStorage.getItem('ms_current');if(c)db.collection('profiles').doc(c).update({status:'offline'}).catch(()=>{});localStorage.removeItem('ms_current');updateUserUI();showToast('Вы вышли из аккаунта')}
function showFormMsg(id,text,type){const el=document.getElementById(id);if(!el)return;el.textContent=text;el.className='form-message '+type;setTimeout(()=>{el.className='form-message'},3000)}
function updateUserUI(){const c=localStorage.getItem('ms_current'),a=document.getElementById('authBtn'),b=document.getElementById('userBadge'),l=document.getElementById('adminLink'),f=document.getElementById('friendsFab');if(c){if(a)a.style.display='none';if(b){b.style.display='flex';b.innerHTML=`<span>${c}</span><span style="cursor:pointer;margin-left:8px" onclick="event.stopPropagation();logout()" title="Выйти"></span>`}if(l)l.style.display=c==='admin'?'inline-block':'none';if(f)f.style.display=c==='admin'?'none':'flex'}else{if(a)a.style.display='inline-block';if(b)b.style.display='none';if(l)l.style.display='none';if(f)f.style.display='none'}updateSupportFab()}
function openProfile(){const u=localStorage.getItem('ms_current');if(!u){openAuth();return}const m=document.getElementById('profileModal');if(m)m.classList.add('active');loadProfile(u)}
function closeProfile(){const m=document.getElementById('profileModal');if(m)m.classList.remove('active')}
async function loadProfile(n){try{const d=await db.collection('profiles').doc(n).get();if(!d.exists)return;const p=d.data(),own=n===localStorage.getItem('ms_current');document.getElementById('profileAvatar').textContent=p.avatar||'👤';document.getElementById('profileNickname').textContent=p.nickname;document.getElementById('profileDescription').textContent=p.description||'Нет описания';document.getElementById('profileStatus').textContent=p.status==='online'?'Онлайн':'Оффлайн';document.getElementById('profileStatus').className='profile-status '+(p.status==='online'?'online':'offline');const bg=document.getElementById('profileBg');if(p.background)bg.style.backgroundImage='url('+p.background+')';else bg.style.backgroundImage='';if(own){document.getElementById('editAvatar').value=p.avatar||'👤';document.getElementById('editDescription').value=p.description||'';document.getElementById('editSection').style.display='block';document.getElementById('friendActions').style.display='none';if(p.background){document.getElementById('backgroundPreview').style.backgroundImage='url('+p.background+')';document.getElementById('backgroundData').value=p.background}else{document.getElementById('backgroundPreview').style.backgroundImage='';document.getElementById('backgroundData').value=''}renderEmojiPicker()}else{document.getElementById('editSection').style.display='none';document.getElementById('friendActions').style.display='block';await updateFriendButton(n)}}catch(e){console.error(e)}}
function renderEmojiPicker(){const p=document.getElementById('emojiPicker');if(!p)return;const c=document.getElementById('editAvatar').value||'';p.innerHTML=EMOJI_LIST.map(e=>`<span class="emoji-option ${e===c?'selected':''}" onclick="selectEmoji('${e}')">${e}</span>`).join('')}
function selectEmoji(e){document.getElementById('editAvatar').value=e;document.querySelectorAll('.emoji-option').forEach(el=>{el.classList.toggle('selected',el.textContent===e)})}
function handleBackgroundUpload(e){const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){showToast('Файл слишком большой (макс. 2 МБ)');return}const r=new FileReader();r.onload=function(ev){document.getElementById('backgroundPreview').style.backgroundImage='url('+ev.target.result+')';document.getElementById('backgroundData').value=ev.target.result};r.readAsDataURL(f)}
function removeBackground(){document.getElementById('backgroundPreview').style.backgroundImage='';document.getElementById('backgroundData').value='';document.getElementById('backgroundFile').value=''}
async function saveProfile(){const u=localStorage.getItem('ms_current');if(!u)return;const a=document.getElementById('editAvatar').value.trim()||'👤',d=document.getElementById('editDescription').value.trim(),b=document.getElementById('backgroundData').value;try{await db.collection('profiles').doc(u).update({avatar:a,description:d,background:b});showToast('Профиль обновлён');loadProfile(u)}catch(e){console.error(e);showToast('Ошибка сохранения')}}
function openFriends(){const u=localStorage.getItem('ms_current');if(!u){openAuth();return}const m=document.getElementById('friendsModal');if(m)m.classList.add('active');loadFriends(u)}
function closeFriends(){const m=document.getElementById('friendsModal');if(m)m.classList.remove('active')}
async function loadFriends(n){try{const d=await db.collection('profiles').doc(n).get();if(!d.exists)return;const f=d.data().friends||[],l=document.getElementById('friendsList');if(f.length===0){l.innerHTML='<div class="support-empty">У тебя пока нет друзей. Найди кого-нибудь через поиск!</div>';return}const items=await Promise.all(f.map(async fn=>{try{const fd=await db.collection('profiles').doc(fn).get();const fr=fd.exists?fd.data():{nickname:fn,avatar:'👤',status:'offline'};return`<div class="friend-item"><div class="friend-avatar">${fr.avatar}</div><div class="friend-info"><div class="friend-name">${fr.nickname}</div><div class="friend-status">${fr.status==='online'?'Онлайн':'Оффлайн'}</div></div><button class="btn btn-primary" style="padding:6px 12px;font-size:12px" onclick="openChat('${fr.nickname}')">Чат</button><button class="btn btn-secondary" style="padding:6px 12px;font-size:12px" onclick="viewProfile('${fr.nickname}')">Профиль</button></div>`}catch(e){return ''}}));l.innerHTML=items.join('')}catch(e){console.error(e)}}
async function searchUsers(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),c=localStorage.getItem('ms_current');if(!q)return;try{const s=await db.collection('profiles').get();const r=s.docs.filter(d=>d.id.toLowerCase().includes(q)&&d.id!==c);const l=document.getElementById('searchResults');if(r.length===0){l.innerHTML='<div class="support-empty">Никто не найден</div>';return}const items=await Promise.all(r.map(async d=>{const p=d.data();const isF=await checkIfFriend(p.nickname);return`<div class="friend-item"><div class="friend-avatar">${p.avatar}</div><div class="friend-info"><div class="friend-name">${p.nickname}</div><div class="friend-status">${p.status==='online'?'Онлайн':'Оффлайн'}</div></div>${isF?'<span style="color:var(--accent-2);font-size:12px">В друзьях</span>':`<button class="btn btn-primary" style="padding:6px 12px;font-size:12px" onclick="addFriend('${p.nickname}')">Добавить</button>`}<button class="btn btn-secondary" style="padding:6px 12px;font-size:12px" onclick="viewProfile('${p.nickname}')">Профиль</button></div>`}));l.innerHTML=items.join('')}catch(e){console.error(e)}}
async function checkIfFriend(n){const c=localStorage.getItem('ms_current');if(!c)return false;try{const d=await db.collection('profiles').doc(c).get();if(!d.exists)return false;return(d.data().friends||[]).includes(n)}catch(e){return false}}
async function addFriend(fn){const u=localStorage.getItem('ms_current');if(!u)return;if(u===fn){showToast('Нельзя добавить себя');return}try{const fd=await db.collection('profiles').doc(fn).get();if(!fd.exists){showToast('Пользователь не найден');return}const ud=await db.collection('profiles').doc(u).get();const f=ud.data().friends||[];if(f.includes(fn)){showToast('Уже в друзьях');return}f.push(fn);await db.collection('profiles').doc(u).update({friends:f});showToast(fn+' добавлен в друзья');loadFriends(u);searchUsers()}catch(e){console.error(e);showToast('Ошибка добавления')}}
async function removeFriend(fn){const u=localStorage.getItem('ms_current');if(!u)return;if(!confirm('Удалить '+fn+' из друзей?'))return;try{const ud=await db.collection('profiles').doc(u).get();const f=(ud.data().friends||[]).filter(n=>n!==fn);await db.collection('profiles').doc(u).update({friends:f});showToast(fn+' удалён из друзей');loadProfile(fn)}catch(e){console.error(e);showToast('Ошибка')}}
async function updateFriendButton(n){const u=localStorage.getItem('ms_current');if(!u||u===n)return;const isF=await checkIfFriend(n),c=document.getElementById('friendActions');if(isF){c.innerHTML=`<button class="btn btn-primary" style="width:100%;margin-bottom:8px" onclick="openChat('${n}')">Написать сообщение</button><button class="btn btn-secondary" style="width:100%;color:#ef4444" onclick="removeFriend('${n}')">Удалить из друзей</button>`}else{c.innerHTML=`<button class="btn btn-primary" style="width:100%" onclick="addFriend('${n}');loadProfile('${n}')">Добавить в друзья</button>`}}
function viewProfile(n){closeFriends();const m=document.getElementById('profileModal');if(m)m.classList.add('active');loadProfile(n)}
let privateChatListener=null;
function openChat(fn){closeFriends();const m=document.getElementById('privateChatModal');if(m)m.classList.add('active');document.getElementById('chatWith').textContent=fn;listenToPrivateChat(fn)}
function closePrivateChat(){const m=document.getElementById('privateChatModal');if(m)m.classList.remove('active');if(privateChatListener){privateChatListener();privateChatListener=null}}
function listenToPrivateChat(fn){const u=localStorage.getItem('ms_current');if(!u)return;if(privateChatListener)privateChatListener();const cid=[u,fn].sort().join('_');privateChatListener=db.collection('private_chats').doc(cid).onSnapshot(doc=>{const b=document.getElementById('privateMessages');if(!doc.exists){b.innerHTML='<div class="support-empty">Начни общение с '+fn+'</div>';return}const ms=doc.data().messages||[];b.innerHTML=ms.map(m=>`<div class="msg ${m.from===u?'msg-user':'msg-friend'}"><div class="msg-text">${escapeHtml(m.text)}</div><div class="msg-time">${formatTime(m.time)}</div></div>`).join('');b.scrollTop=b.scrollHeight})}
async function sendPrivateMessage(e){e.preventDefault();const u=localStorage.getItem('ms_current'),fn=document.getElementById('chatWith').textContent,i=document.getElementById('privateInput'),t=i.value.trim();if(!t||!fn)return;const cid=[u,fn].sort().join('_');try{const d=await db.collection('private_chats').doc(cid).get();if(!d.exists){await db.collection('private_chats').doc(cid).set({users:[u,fn],messages:[{from:u,text:t,time:Date.now(),read:false}],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{const ms=d.data().messages||[];ms.push({from:u,text:t,time:Date.now(),read:false});await d.ref.update({messages:ms})}i.value=''}catch(e){console.error(e);showToast('Ошибка отправки')}}
let supportListener=null;
function openSupport(){const u=localStorage.getItem('ms_current');if(!u){openAuth();showToast('Сначала войди в аккаунт');return}if(u==='admin'){window.location.href='admin.html';return}const m=document.getElementById('supportModal');if(m)m.classList.add('active');listenToPlayerChat()}
function closeSupport(){const m=document.getElementById('supportModal');if(m)m.classList.remove('active');if(supportListener){supportListener();supportListener=null}}
function listenToPlayerChat(){const u=localStorage.getItem('ms_current');if(!u)return;if(supportListener)supportListener();supportListener=db.collection('support').where('user','==',u).onSnapshot(s=>{if(s.empty){db.collection('support').add({user:u,messages:[],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{renderPlayerChat(s.docs[0].data().messages||[])}})}
function renderPlayerChat(ms){const b=document.getElementById('playerMessages');if(!b)return;if(ms.length===0){b.innerHTML='<div class="support-empty">Напиши свой вопрос — админ ответит в ближайшее время</div>'}else{b.innerHTML=ms.map(m=>`<div class="msg ${m.from==='admin'?'msg-admin':'msg-user'}"><div class="msg-text">${escapeHtml(m.text)}</div><div class="msg-time">${formatTime(m.time)}</div></div>`).join('');b.scrollTop=b.scrollHeight}}
async function sendPlayerMessage(e){e.preventDefault();const u=localStorage.getItem('ms_current');if(!u)return;const i=document.getElementById('playerInput'),t=i.value.trim();if(!t)return;try{const s=await db.collection('support').where('user','==',u).get();if(s.empty){await db.collection('support').add({user:u,messages:[{from:u,text:t,time:Date.now(),read:false}],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{const d=s.docs[0],ms=d.data().messages||[];ms.push({from:u,text:t,time:Date.now(),read:false});await d.ref.update({messages:ms})}i.value='';showToast('Сообщение отправлено')}catch(e){console.error(e);showToast('Ошибка отправки')}}
function updateSupportFab(){const f=document.getElementById('supportFab');if(!f)return;const u=localStorage.getItem('ms_current');if(!u||u==='admin'){f.style.display='none';return}f.style.display='flex';db.collection('support').where('user','==',u).onSnapshot(s=>{if(!s.empty){const ms=s.docs[0].data().messages||[];const un=ms.filter(m=>m.from==='admin'&&!m.read).length;const b=f.querySelector('.fab-badge');if(b){if(un>0){b.style.display='flex';b.textContent=un}else{b.style.display='none'}}}})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatTime(ts){const d=new Date(ts),diff=(Date.now()-d)/1000;if(diff<60)return'только что';if(diff<3600)return Math.floor(diff/60)+' мин назад';if(diff<86400)return Math.floor(diff/3600)+' ч назад';return d.toLocaleDateString('ru-RU')}
function animateCounter(el){const t=el.textContent,m=t.match(/[\d.]+/);if(!m)return;const target=parseFloat(m[0].replace(/\s/g,''));let c=0;const step=target/40;const iv=setInterval(()=>{c+=step;if(c>=target){c=target;clearInterval(iv)}el.textContent=Math.floor(c).toLocaleString('ru-RU').replace(/,/g,' ')},30)}
function initScrollTop(){const b=document.querySelector('.scroll-top');if(!b)return;window.addEventListener('scroll',()=>{if(window.scrollY>400)b.classList.add('visible');else b.classList.remove('visible')});b.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}))}
function initActiveLink(){const c=window.location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(l=>{if(l.getAttribute('href')===c)l.classList.add('active')})}
document.addEventListener('DOMContentLoaded',()=>{ensureAdmin();updateUserUI();initScrollTop();initActiveLink();document.querySelectorAll('.stat-num').forEach(el=>{const o=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){animateCounter(el);o.disconnect()}});o.observe(el)})});
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-overlay')){closeAuth();closeSupport();closeProfile();closeFriends();closePrivateChat()}});
