const firebaseConfig={apiKey:"AIzaSyBX496oLlIFMD36SvyOl5zczX8d3vbvWEU",authDomain:"mineserver-bb0c6.firebaseapp.com",databaseURL:"https://mineserver-bb0c6-default-rtdb.europe-west1.firebasedatabase.app",projectId:"mineserver-bb0c6",storageBucket:"mineserver-bb0c6.firebasestorage.app",messagingSenderId:"630624618107",appId:"1:630624618107:web:4b2fdc9f2b7aaed44a44de",measurementId:"G-TEVM88WW3P"};
firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
const EMOJI_LIST=['👤','','⚔️','🛡️','🧙','🧝','','🐺','💀','','🎯','❄️','','☀️','🍀','','🔮','🗡️','','🌊','🎨','','🎧','🎬','⭐','🌟','💫','','🎳','🎪'];
const CHAT_EMOJI=['😀','😃','😄','😁','😆','😅','🤣','','🙂','🙃','😉','😊','😇','🥰','','🤩','😘','😗','😚','😙','🥲','','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','','🤐','🤨','','😑','😶','','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷','🤒','','🤢','🤮','🥵','🥶','','😵','🤯','🤠','🥳','🥸','','🤓','🧐','😕','😟','🙁','️','😮','😯','','😳','🥺','','😧','😨','😰','','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','','👿','💀','️','💩','🤡','👹','👺','👻','👽','👾','','😺','😸','','😻','😼','😽','🙀','😿','😾','❤️','🧡','💛','','💙','💜','','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','','💝','💟','👍','👎','👊','','🤛','🤜','','🙌','👐','','🤝','🙏','️','🤞','🤟','','🤙','👈','👉','👆','','👇','☝️','','🤚','️','✋','🖖','👌','🤌','','✋'];

document.addEventListener('copy',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();showToast('Копирование запрещено')});
document.addEventListener('cut',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault()});
document.addEventListener('contextmenu',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault();showToast('Правый клик отключён')});
document.addEventListener('selectstart',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;e.preventDefault()});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if((e.ctrlKey&&['c','C','u','U','a','A','s','S'].includes(e.key))||e.key==='F12'||(e.ctrlKey&&e.shiftKey&&['I','i','J','j'].includes(e.key))){e.preventDefault();showToast('Действие заблокировано')}});

function copyIP(el){const ip=el.dataset.ip||'play.reished.ru';navigator.clipboard.writeText(ip).then(()=>{el.classList.add('copied');const c=el.querySelector('.copy');if(c){c.textContent='✓ скопировано';setTimeout(()=>{c.textContent='скопировать'},1500)}showToast('IP скопирован: '+ip)})}
function showToast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2000)}

async function ensureAdmin(){try{const a=await db.collection('users').doc('admin').get();if(!a.exists){await db.collection('users').doc('admin').set({password:'admin123',role:'admin',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('profiles').doc('admin').set({nickname:'admin',avatar:'👑',description:'Основатель сервера',status:'online',friends:[],background:''})}}catch(e){console.error(e)}}
function isAdmin(){return localStorage.getItem('ms_current')==='admin'}

function openAuth(){const m=document.getElementById('authModal');if(m)m.classList.add('active')}
function closeAuth(){const m=document.getElementById('authModal');if(m)m.classList.remove('active')}
function switchTab(tab){document.querySelectorAll('.modal-tab').forEach(t=>t.classList.remove('active'));document.querySelector(`.modal-tab[data-tab="${tab}"]`)?.classList.add('active');const l=document.getElementById('loginForm'),r=document.getElementById('registerForm');if(l)l.style.display=tab==='login'?'block':'none';if(r)r.style.display=tab==='register'?'block':'none'}

async function handleLogin(e){e.preventDefault();const n=document.getElementById('loginNick').value.trim(),p=document.getElementById('loginPass').value;try{const d=await db.collection('users').doc(n).get();if(!d.exists){showFormMsg('loginMsg','Пользователь не найден','error');return}if(d.data().password!==p){showFormMsg('loginMsg','Неверный пароль','error');return}localStorage.setItem('ms_current',n);await db.collection('profiles').doc(n).update({status:'online'});updateUserUI();closeAuth();showToast('Добро пожаловать, '+n+'!');if(n==='admin')setTimeout(()=>window.location.href='admin.html',800)}catch(e){console.error(e);showFormMsg('loginMsg','Ошибка входа','error')}}

async function handleRegister(e){e.preventDefault();const n=document.getElementById('regNick').value.trim(),p=document.getElementById('regPass').value,c=document.getElementById('regConfirm').value;if(n.toLowerCase()==='admin'){showFormMsg('regMsg','Этот ник зарезервирован','error');return}if(n.length<3){showFormMsg('regMsg','Ник минимум 3 символа','error');return}if(p.length<4){showFormMsg('regMsg','Пароль минимум 4 символа','error');return}if(p!==c){showFormMsg('regMsg','Пароли не совпадают','error');return}try{const s=await db.collection('users').get();const ex=s.docs.find(d=>d.id.toLowerCase()===n.toLowerCase());if(ex){showFormMsg('regMsg','Ник "'+ex.id+'" уже занят','error');return}await db.collection('users').doc(n).set({password:p,role:'player',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection('profiles').doc(n).set({nickname:n,avatar:'👤',description:'Новый игрок',status:'online',friends:[],background:''});localStorage.setItem('ms_current',n);updateUserUI();closeAuth();showToast('Регистрация успешна! Привет, '+n+'!')}catch(e){console.error(e);showFormMsg('regMsg','Ошибка регистрации','error')}}

function logout(){if(!confirm('Выйти из аккаунта?'))return;const c=localStorage.getItem('ms_current');if(c)db.collection('profiles').doc(c).update({status:'offline'}).catch(()=>{});localStorage.removeItem('ms_current');updateUserUI();showToast('Вы вышли из аккаунта')}

function showFormMsg(id,text,type){const el=document.getElementById(id);if(!el)return;el.textContent=text;el.className='form-message '+type;setTimeout(()=>{el.className='form-message'},3000)}

function updateUserUI(){const c=localStorage.getItem('ms_current'),a=document.getElementById('authBtn'),b=document.getElementById('userBadge'),l=document.getElementById('adminLink'),f=document.getElementById('friendsFab');if(c){if(a)a.style.display='none';if(b){b.style.display='flex';b.innerHTML=`<span>${c}</span><span style="cursor:pointer;margin-left:8px;color:var(--danger)" onclick="event.stopPropagation();logout()" title="Выйти">✕</span>`}if(l)l.style.display=c==='admin'?'inline-block':'none';if(f)f.style.display=c==='admin'?'none':'flex'}else{if(a)a.style.display='inline-block';if(b)b.style.display='none';if(l)l.style.display='none';if(f)f.style.display='none'}updateSupportFab();loadFriendRequestsCount()}

// ===== ПРОФИЛЬ =====
function openProfile(){const u=localStorage.getItem('ms_current');if(!u){openAuth();return}const m=document.getElementById('profileModal');if(m)m.classList.add('active');loadProfile(u)}
function closeProfile(){const m=document.getElementById('profileModal');if(m)m.classList.remove('active')}
async function loadProfile(n){try{const d=await db.collection('profiles').doc(n).get();if(!d.exists)return;const p=d.data(),own=n===localStorage.getItem('ms_current');document.getElementById('profileAvatar').textContent=p.avatar||'👤';document.getElementById('profileNickname').textContent=p.nickname;document.getElementById('profileDescription').textContent=p.description||'Нет описания';document.getElementById('profileStatus').textContent=p.status==='online'?'Онлайн':'Оффлайн';document.getElementById('profileStatus').className='profile-status '+(p.status==='online'?'online':'offline');const bg=document.getElementById('profileBg');if(p.background)bg.style.backgroundImage='url('+p.background+')';else bg.style.backgroundImage='';if(own){document.getElementById('editAvatar').value=p.avatar||'👤';document.getElementById('editDescription').value=p.description||'';document.getElementById('editSection').style.display='block';document.getElementById('friendActions').style.display='none';if(p.background){document.getElementById('backgroundPreview').style.backgroundImage='url('+p.background+')';document.getElementById('backgroundData').value=p.background}else{document.getElementById('backgroundPreview').style.backgroundImage='';document.getElementById('backgroundData').value=''}renderEmojiPicker()}else{document.getElementById('editSection').style.display='none';document.getElementById('friendActions').style.display='block';await updateFriendButton(n)}}catch(e){console.error(e)}}

function renderEmojiPicker(){const p=document.getElementById('emojiPicker');if(!p)return;const c=document.getElementById('editAvatar').value||'';p.innerHTML=EMOJI_LIST.map(e=>`<span class="emoji-option ${e===c?'selected':''}" onclick="selectEmoji('${e}')">${e}</span>`).join('')}
function selectEmoji(e){document.getElementById('editAvatar').value=e;document.querySelectorAll('.emoji-option').forEach(el=>{el.classList.toggle('selected',el.textContent===e)})}
function handleBackgroundUpload(e){const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){showToast('Файл слишком большой (макс. 2 МБ)');return}const r=new FileReader();r.onload=function(ev){document.getElementById('backgroundPreview').style.backgroundImage='url('+ev.target.result+')';document.getElementById('backgroundData').value=ev.target.result};r.readAsDataURL(f)}
function removeBackground(){document.getElementById('backgroundPreview').style.backgroundImage='';document.getElementById('backgroundData').value='';document.getElementById('backgroundFile').value=''}
async function saveProfile(){const u=localStorage.getItem('ms_current');if(!u)return;const a=document.getElementById('editAvatar').value.trim()||'👤',d=document.getElementById('editDescription').value.trim(),b=document.getElementById('backgroundData').value;try{await db.collection('profiles').doc(u).update({avatar:a,description:d,background:b});showToast('Профиль обновлён');loadProfile(u)}catch(e){console.error(e);showToast('Ошибка сохранения')}}

// ===== ДРУЗЬЯ (через запросы) =====
async function loadFriendRequestsCount(){const u=localStorage.getItem('ms_current');if(!u)return;try{const s=await db.collection('friend_requests').where('to','==',u).where('status','==','pending').get();const count=s.size;const fab=document.getElementById('friendsFab');if(fab){let badge=fab.querySelector('.fab-badge');if(!badge){badge=document.createElement('span');badge.className='fab-badge';fab.appendChild(badge)}if(count>0){badge.style.display='flex';badge.textContent=count}else{badge.style.display='none'}}}catch(e){}}

async function sendFriendRequest(toNick){const from=localStorage.getItem('ms_current');if(!from){openAuth();return}if(from===toNick){showToast('Нельзя отправить себе');return}try{const existing=await db.collection('friend_requests').where('from','==',from).where('to','==',toNick).get();if(!existing.empty){showToast('Запрос уже отправлен');return}const reverse=await db.collection('friend_requests').where('from','==',toNick).where('to','==',from).where('status','==','pending').get();if(!reverse.empty){showToast('У вас уже есть запрос от '+toNick);return}await db.collection('friend_requests').add({from,to:toNick,status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()});showToast('Запрос отправлен '+toNick)}catch(e){console.error(e);showToast('Ошибка отправки запроса')}}

async function loadFriendRequests(){const u=localStorage.getItem('ms_current');if(!u)return;try{const incoming=await db.collection('friend_requests').where('to','==',u).where('status','==','pending').get();const outgoing=await db.collection('friend_requests').where('from','==',u).where('status','==','pending').get();const inc=incoming.docs.map(d=>({id:d.id,...d.data()}));const out=outgoing.docs.map(d=>({id:d.id,...d.data()}));const incList=document.getElementById('incomingRequests');const outList=document.getElementById('outgoingRequests');if(inc.length===0){incList.innerHTML='<div class="support-empty">Нет входящих запросов</div>'}else{incList.innerHTML=(await Promise.all(inc.map(async r=>{const fd=await db.collection('profiles').doc(r.from).get();const f=fd.exists?fd.data():{nickname:r.from,avatar:'👤'};return`<div class="friend-request-item"><div class="avatar">${f.avatar}</div><div class="info"><div class="friend-name">${f.nickname}</div></div><div class="actions"><button class="btn btn-primary" style="padding:5px 10px;font-size:11px" onclick="acceptRequest('${r.id}','${r.from}')">Принять</button><button class="btn btn-secondary" style="padding:5px 10px;font-size:11px" onclick="declineRequest('${r.id}')">Отклонить</button></div></div>`}))).join('')}if(out.length===0){outList.innerHTML='<div class="support-empty">Нет исходящих запросов</div>'}else{outList.innerHTML=(await Promise.all(out.map(async r=>{const fd=await db.collection('profiles').doc(r.to).get();const f=fd.exists?fd.data():{nickname:r.to,avatar:'👤'};return`<div class="friend-request-item"><div class="avatar">${f.avatar}</div><div class="info"><div class="friend-name">${f.nickname}</div><div class="friend-status">Ожидает ответа</div></div><button class="btn btn-secondary" style="padding:5px 10px;font-size:11px" onclick="cancelRequest('${r.id}')">Отменить</button></div>`}))).join('')}}catch(e){console.error(e)}}

async function acceptRequest(reqId,fromNick){const u=localStorage.getItem('ms_current');try{await db.collection('friend_requests').doc(reqId).update({status:'accepted'});const ud=await db.collection('profiles').doc(u).get();const uf=(ud.data().friends||[]);if(!uf.includes(fromNick))uf.push(fromNick);await db.collection('profiles').doc(u).update({friends:uf});const fd=await db.collection('profiles').doc(fromNick).get();const ff=(fd.data().friends||[]);if(!ff.includes(u))ff.push(u);await db.collection('profiles').doc(fromNick).update({friends:ff});showToast('Запрос принят');loadFriends(u);loadFriendRequests()}catch(e){console.error(e);showToast('Ошибка')}}

async function declineRequest(reqId){try{await db.collection('friend_requests').doc(reqId).update({status:'declined'});showToast('Запрос отклонён');loadFriendRequests()}catch(e){console.error(e)}}

async function cancelRequest(reqId){try{await db.collection('friend_requests').doc(reqId).delete();showToast('Запрос отменён');loadFriendRequests()}catch(e){console.error(e)}}

function openFriends(){const u=localStorage.getItem('ms_current');if(!u){openAuth();return}const m=document.getElementById('friendsModal');if(m)m.classList.add('active');loadFriends(u);loadFriendRequests()}
function closeFriends(){const m=document.getElementById('friendsModal');if(m)m.classList.remove('active')}

async function loadFriends(n){try{const d=await db.collection('profiles').doc(n).get();if(!d.exists)return;const f=d.data().friends||[],l=document.getElementById('friendsList');if(f.length===0){l.innerHTML='<div class="support-empty">У тебя пока нет друзей</div>';return}const items=await Promise.all(f.map(async fn=>{try{const fd=await db.collection('profiles').doc(fn).get();const fr=fd.exists?fd.data():{nickname:fn,avatar:'👤',status:'offline'};return`<div class="friend-item"><div class="friend-avatar">${fr.avatar}</div><div class="friend-info"><div class="friend-name">${fr.nickname}</div><div class="friend-status">${fr.status==='online'?'Онлайн':'Оффлайн'}</div></div><button class="btn btn-primary" style="padding:5px 10px;font-size:11px" onclick="openChat('${fr.nickname}')">Чат</button><button class="btn btn-secondary" style="padding:5px 10px;font-size:11px" onclick="viewProfile('${fr.nickname}')">Профиль</button></div>`}catch(e){return ''}}));l.innerHTML=items.join('')}catch(e){console.error(e)}}

async function searchUsers(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),c=localStorage.getItem('ms_current');if(!q)return;try{const s=await db.collection('profiles').get();const r=s.docs.filter(d=>d.id.toLowerCase().includes(q)&&d.id!==c);const l=document.getElementById('searchResults');if(r.length===0){l.innerHTML='<div class="support-empty">Никто не найден</div>';return}const items=await Promise.all(r.map(async d=>{const p=d.data();const isF=(p.friends||[]).includes(c);return`<div class="friend-item"><div class="friend-avatar">${p.avatar}</div><div class="friend-info"><div class="friend-name">${p.nickname}</div><div class="friend-status">${p.status==='online'?'Онлайн':'Оффлайн'}</div></div>${isF?'<span style="color:var(--accent-2);font-size:11px">В друзьях</span>':`<button class="btn btn-primary" style="padding:5px 10px;font-size:11px" onclick="sendFriendRequest('${p.nickname}')">Добавить</button>`}<button class="btn btn-secondary" style="padding:5px 10px;font-size:11px" onclick="viewProfile('${p.nickname}')">Профиль</button></div>`}));l.innerHTML=items.join('')}catch(e){console.error(e)}}

async function updateFriendButton(n){const u=localStorage.getItem('ms_current');if(!u||u===n)return;const c=document.getElementById('friendActions');try{const req=await db.collection('friend_requests').where('from','==',u).where('to','==',n).get();const req2=await db.collection('friend_requests').where('from','==',n).where('to','==',u).where('status','==','pending').get();const prof=await db.collection('profiles').doc(n).get();const isF=(prof.data().friends||[]).includes(u);if(isF){c.innerHTML=`<button class="btn btn-primary" style="width:100%;margin-bottom:6px" onclick="openChat('${n}')">Написать сообщение</button><button class="btn btn-secondary" style="width:100%;color:var(--danger)" onclick="removeFriend('${n}')">Удалить из друзей</button>`}else if(!req.empty){c.innerHTML=`<button class="btn btn-secondary" style="width:100%" disabled>Запрос отправлен</button>`}else if(!req2.empty){c.innerHTML=`<button class="btn btn-primary" style="width:100%" onclick="acceptPending('${n}')">Принять запрос в друзья</button>`}else{c.innerHTML=`<button class="btn btn-primary" style="width:100%" onclick="sendFriendRequest('${n}');loadProfile('${n}')">Отправить запрос в друзья</button>`}}catch(e){console.error(e)}}

async function acceptPending(n){const u=localStorage.getItem('ms_current');try{const req=await db.collection('friend_requests').where('from','==',n).where('to','==',u).where('status','==','pending').get();if(!req.empty){const reqId=req.docs[0].id;await acceptRequest(reqId,n);loadProfile(n)}}catch(e){console.error(e)}}

async function removeFriend(fn){const u=localStorage.getItem('ms_current');if(!u)return;if(!confirm('Удалить '+fn+' из друзей?'))return;try{const ud=await db.collection('profiles').doc(u).get();const f=(ud.data().friends||[]).filter(n=>n!==fn);await db.collection('profiles').doc(u).update({friends:f});const fd=await db.collection('profiles').doc(fn).get();const ff=(fd.data().friends||[]).filter(n=>n!==u);await db.collection('profiles').doc(fn).update({friends:ff});showToast(fn+' удалён из друзей');loadProfile(fn)}catch(e){console.error(e);showToast('Ошибка')}}

function viewProfile(n){closeFriends();const m=document.getElementById('profileModal');if(m)m.classList.add('active');loadProfile(n)}

// ===== ЛИЧНЫЕ СООБЩЕНИЯ =====
let privateChatListener=null;
function openChat(fn){closeFriends();const m=document.getElementById('privateChatModal');if(m)m.classList.add('active');document.getElementById('chatWith').textContent=fn;listenToPrivateChat(fn)}
function closePrivateChat(){const m=document.getElementById('privateChatModal');if(m)m.classList.remove('active');if(privateChatListener){privateChatListener();privateChatListener=null}}
function listenToPrivateChat(fn){const u=localStorage.getItem('ms_current');if(!u)return;if(privateChatListener)privateChatListener();const cid=[u,fn].sort().join('_');privateChatListener=db.collection('private_chats').doc(cid).onSnapshot(doc=>{const b=document.getElementById('privateMessages');if(!doc.exists){b.innerHTML='<div class="support-empty">Начни общение с '+fn+'</div>';return}const ms=doc.data().messages||[];b.innerHTML=ms.map(m=>`<div class="msg ${m.from===u?'msg-user':'msg-friend'}"><div class="msg-text">${escapeHtml(m.text)}</div><div class="msg-time">${formatTime(m.time)}</div></div>`).join('');b.scrollTop=b.scrollHeight})}
async function sendPrivateMessage(e){e.preventDefault();const u=localStorage.getItem('ms_current'),fn=document.getElementById('chatWith').textContent,i=document.getElementById('privateInput'),t=i.value.trim();if(!t||!fn)return;const cid=[u,fn].sort().join('_');try{const d=await db.collection('private_chats').doc(cid).get();if(!d.exists){await db.collection('private_chats').doc(cid).set({users:[u,fn],messages:[{from:u,text:t,time:Date.now(),read:false}],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{const ms=d.data().messages||[];ms.push({from:u,text:t,time:Date.now(),read:false});await d.ref.update({messages:ms})}i.value=''}catch(e){console.error(e);showToast('Ошибка отправки')}}

// ===== ПОДДЕРЖКА =====
let supportListener=null;
function openSupport(){const u=localStorage.getItem('ms_current');if(!u){openAuth();showToast('Сначала войди в аккаунт');return}if(u==='admin'){window.location.href='admin.html';return}const m=document.getElementById('supportModal');if(m)m.classList.add('active');listenToPlayerChat()}
function closeSupport(){const m=document.getElementById('supportModal');if(m)m.classList.remove('active');if(supportListener){supportListener();supportListener=null}}
function listenToPlayerChat(){const u=localStorage.getItem('ms_current');if(!u)return;if(supportListener)supportListener();supportListener=db.collection('support').where('user','==',u).onSnapshot(s=>{if(s.empty){db.collection('support').add({user:u,messages:[],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{renderPlayerChat(s.docs[0].data().messages||[])}})}
function renderPlayerChat(ms){const b=document.getElementById('playerMessages');if(!b)return;if(ms.length===0){b.innerHTML='<div class="support-empty">Напиши свой вопрос — админ ответит в ближайшее время</div>'}else{b.innerHTML=ms.map(m=>`<div class="msg ${m.from==='admin'?'msg-admin':'msg-user'}"><div class="msg-text">${escapeHtml(m.text)}</div><div class="msg-time">${formatTime(m.time)}</div></div>`).join('');b.scrollTop=b.scrollHeight}}
async function sendPlayerMessage(e){e.preventDefault();const u=localStorage.getItem('ms_current');if(!u)return;const i=document.getElementById('playerInput'),t=i.value.trim();if(!t)return;try{const s=await db.collection('support').where('user','==',u).get();if(s.empty){await db.collection('support').add({user:u,messages:[{from:u,text:t,time:Date.now(),read:false}],createdAt:firebase.firestore.FieldValue.serverTimestamp()})}else{const d=s.docs[0],ms=d.data().messages||[];ms.push({from:u,text:t,time:Date.now(),read:false});await d.ref.update({messages:ms})}i.value='';showToast('Сообщение отправлено')}catch(e){console.error(e);showToast('Ошибка отправки')}}
function insertEmoji(emoji){const i=document.getElementById('playerInput');i.value+=emoji;i.focus()}
function toggleEmojiPicker(){const p=document.getElementById('emojiChatPicker');p.style.display=p.style.display==='none'?'flex':'none'}

function updateSupportFab(){const f=document.getElementById('supportFab');if(!f)return;const u=localStorage.getItem('ms_current');if(!u||u==='admin'){f.style.display='none';return}f.style.display='flex';db.collection('support').where('user','==',u).onSnapshot(s=>{if(!s.empty){const ms=s.docs[0].data().messages||[];const un=ms.filter(m=>m.from==='admin'&&!m.read).length;const b=f.querySelector('.fab-badge');if(b){if(un>0){b.style.display='flex';b.textContent=un}else{b.style.display='none'}}}})}

function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatTime(ts){const d=new Date(ts),diff=(Date.now()-d)/1000;if(diff<60)return'только что';if(diff<3600)return Math.floor(diff/60)+' мин назад';if(diff<86400)return Math.floor(diff/3600)+' ч назад';return d.toLocaleDateString('ru-RU')}
function animateCounter(el){const t=el.textContent,m=t.match(/[\d.]+/);if(!m)return;const target=parseFloat(m[0].replace(/\s/g,''));let c=0;const step=target/40;const iv=setInterval(()=>{c+=step;if(c>=target){c=target;clearInterval(iv)}el.textContent=Math.floor(c).toLocaleString('ru-RU').replace(/,/g,' ')},30)}
function initScrollTop(){const b=document.querySelector('.scroll-top');if(!b)return;window.addEventListener('scroll',()=>{if(window.scrollY>400)b.classList.add('visible');else b.classList.remove('visible')});b.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}))}
function initActiveLink(){const c=window.location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(l=>{if(l.getAttribute('href')===c)l.classList.add('active')})}

document.addEventListener('DOMContentLoaded',()=>{ensureAdmin();updateUserUI();initScrollTop();initActiveLink();document.querySelectorAll('.stat-num').forEach(el=>{const o=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){animateCounter(el);o.disconnect()}});o.observe(el)})});
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-overlay')){closeAuth();closeSupport();closeProfile();closeFriends();closePrivateChat()}});
